apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-stack-k8s.yml
    kompose.version: 1.11.0 (39ad614)
  labels:
    io.kompose.service: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: worker
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: worker
    spec:
      containers:
      - image: swr.cn-south-1.myhuaweicloud.com/ucs-dev-org/worker:20230705.1
        name: worker
      imagePullSecrets:
      - name: default-secret
      restartPolicy: Always
