apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-stack-k8s.yml
    kompose.version: 1.11.0 (39ad614)
    kubernetes.io/elb.class: performance
    kubernetes.io/elb.autocreate: 
        '{
            "type": "public",
            "bandwidth_name": "cce-bandwidth-1626694478577",
            "bandwidth_chargemode": "bandwidth",
            "bandwidth_size": 5,
            "bandwidth_sharetype": "PER",
            "eip_type": "5_bgp",
            "available_zone": [
                "cn-south-1a"
            ],
            "l4_flavor_name": "L4_flavor.elb.s1.small"
        }'
  labels:
    io.kompose.service: vote
  name: vote
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 80
  selector:
    io.kompose.service: vote
status:
  loadBalancer: {}
