apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base/cache
  - ../base/database
  - ../base/backend-worker
  - ../base/frontend-vote
  - ../base/frontend-result
patches:
- target:
    kind: Deployment
    name: vote
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: swr.ap-southeast-3.myhuaweicloud.com/ucs/vote:2024.1.16.05
