apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-stack-k8s.yml
    kompose.version: 1.11.0 (39ad614)
  labels:
    io.kompose.service: result
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: result
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: result
    spec:
      containers:
      - image: swr.cn-south-1.myhuaweicloud.com/ucs-dev-org/result:20230705.1
        name: result
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: default-secret
      restartPolicy: Always
