# UCS Demo
name: UCS CICD Demo For Phoniex Store Web Service - vote
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    - run: echo "Now, Building image for vote service. "
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: | 
        docker build -f vote/Dockerfile -t vote:latest .
    - run: |
        docker login -u ap-southeast-3@4HY7CDIS5D51NXYXHCO4 -p e19abd6b44103f53c6871258a78dabd3c2f875e3e414752354bc6250ea80863e swr.ap-southeast-3.myhuaweicloud.com
    - run: |
        sudo docker tag vote:latest swr.ap-southeast-3.myhuaweicloud.com/ucs/vote:latest
    - run: |
        sudo docker push swr.ap-southeast-3.myhuaweicloud.com/ucs/vote:latest
    

