# UCS Demo
name: Vote Service Building Process For UCS CICD Demo.
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    - run: echo "Now, Building image for vote service. "
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: | 
        docker build -f vote/Dockerfile -t vote:latest .     
    - run: |
        sudo docker tag vote:latest swr.ap-southeast-3.myhuaweicloud.com/ucs/vote:latest
    - run: |
        docker login -u ap-southeast-3@5J2MA2JSWPXFI6EMJUQG -p 3e12d69f701d900aefc593cbf98620c8c68d9683db008a7f2e396db0edd7fe63 swr.ap-southeast-3.myhuaweicloud.com && \
        sudo docker push swr.ap-southeast-3.myhuaweicloud.com/ucs/vote:latest
    

