# UCS Demo
name: Vote Service Building Process For UCS CICD Demo.
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    - run: echo "Now, Building image for vote service. "
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: | 
        docker build -f vote/Dockerfile -t vote:latest .     
    - run: |
        sudo docker tag vote:latest swr.ap-southeast-3.myhuaweicloud.com/ucs/vote:latest
    - run: |
        docker login -u ap-southeast-3@079JG17Z13NO2YVV2J4I -p 9e1e3d416cefd425773d7b32743fa8510625de40d644fee146df38c85d3dd5c2 swr.ap-southeast-3.myhuaweicloud.com && \
        sudo docker push swr.ap-southeast-3.myhuaweicloud.com/ucs/vote:latest
    

