# UCS Demo
name: Vote Service Building Process For UCS CICD Demo.
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    - run: echo "Now, Building image for vote service. "
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: | 
        docker build -f vote/Dockerfile -t vote:latest .     
    - run: |
        sudo docker tag vote:latest swr.ap-southeast-3.myhuaweicloud.com/ucs/vote:latest
    - run: |
        sudo docker login -u ap-southeast-3@RDLE5HYWOZBQQPRZK6JM -p 568dc9892b6e0a1f75d7192a7925e5af170968a8df1a83fb2f8a3a6f230e2a3e swr.ap-southeast-3.myhuaweicloud.com
    - run: |  
        sudo cat /root/.docker/config.json
    - run: |
        sudo docker push swr.ap-southeast-3.myhuaweicloud.com/ucs/vote:latest
    

