# UCS Demo
name: Phoniex Service Building Process For UCS CICD Demo. 
on: [push]

env:
  IMAGE_TAG: 2024.1.16.01
  DOCKER_LOGIN: docker login -u ap-southeast-3@5J2MA2JSWPXFI6EMJUQG -p 3e12d69f701d900aefc593cbf98620c8c68d9683db008a7f2e396db0edd7fe63 swr.ap-southeast-3.myhuaweicloud.com
  
jobs:
  build-vote-service:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build Image
      run: | 
        docker build -f vote/Dockerfile -t vote:latest .     
    - run: |
        sudo docker tag vote:latest swr.ap-southeast-3.myhuaweicloud.com/ucs/vote:$IMAGE_TAG
    - run: |
        sudo $DOCKER_LOGIN
    - run: |
        sudo docker push swr.ap-southeast-3.myhuaweicloud.com/ucs/vote:$IMAGE_TAG
  build-result-service:
    needs: build-vote-service
    runs-on: ubuntu-latest
    steps:
      - run: echo "test 2"
  build-worker-service:
    needs: build-result-service
    runs-on: ubuntu-latest
    steps:
      - run: echo "test 3"
